# Generated by Django 6.0.4 on 2026-04-18 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category_post_notification_comment_bookmark"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-date"], "verbose_name_plural": "Notifications"},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="dscription",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="post",
            name="Category",
        ),
        migrations.RemoveField(
            model_name="post",
            name="view",
        ),
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="viewed_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default/default-user.jpg",
                null=True,
                upload_to="image",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="api.category",
            ),
        ),
    ]
