# Generated by Django 6.0.4 on 2026-04-19 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_category_options_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Likes",
            field=models.ManyToManyField(
                blank=True, related_name="Likes_User", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="post",
            name="views",
        ),
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
