# Generated by Django 6.0.4 on 2026-04-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
