# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_user_otp_user_reset_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("Like", "Like"),
                    ("Comment", "Comment"),
                    ("Bookmark", "Bookmark"),
                ],
                max_length=100,
            ),
        ),
    ]
