# Generated by Django 6.0.4 on 2026-04-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_user_otp_expiry_alter_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
